CREATE TABLE Planes
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(30) NOT NULL,
	Seats INT NOT NULL,
	[Range] INT NOT NULL 
)

CREATE TABLE Flights
(
	Id INT PRIMARY KEY IDENTITY,
	DepartureTime DATETIME,
	ArrivalTime DATETIME,
	Origin NVARCHAR(50) NOT NULL,
	Destination NVARCHAR(50) NOT NULL,
	PlaneId INT NOT NULL,

	CONSTRAINT FK_Flights_PlaneId
	FOREIGN KEY(PlaneId)
	REFERENCES Planes(Id)
)

CREATE TABLE Passengers
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Age INT NOT NULL,
	[Address] NVARCHAR(30) NOT NULL,
	PassportId NVARCHAR(11) NOT NULL
)

CREATE TABLE LuggageTypes
(
	Id INT PRIMARY KEY IDENTITY,
	[Type] NVARCHAR(30) NOT NULL
)

CREATE TABLE Luggages
(
	Id INT PRIMARY KEY IDENTITY,
	LuggageTypeId INT NOT NULL,
	PassengerId INT NOT NULL,

	CONSTRAINT FK_Luggages_LuggageTypeId
	FOREIGN KEY(LuggageTypeId)
	REFERENCES LuggageTypes(Id),

	CONSTRAINT FK_Luggages_PassengerId
	FOREIGN KEY(PassengerId)
	REFERENCES Passengers(Id)
)

CREATE TABLE Tickets
(
	Id INT PRIMARY KEY IDENTITY,
	PassengerId INT NOT NULL,
	FlightId INT NOT NULL,
	LuggageId INT NOT NULL,
	Price DECIMAL(15,2) NOT NULL

	CONSTRAINT FK_Tickets_PassangerId
	FOREIGN KEY(PassengerId)
	REFERENCES Passengers(Id),

	CONSTRAINT FK_Tickets_FlightId
	FOREIGN KEY(FlightId)
	REFERENCES Flights(Id),

	CONSTRAINT FK_Tickets_LuggageId
	FOREIGN KEY(LuggageId)
	REFERENCES Luggages(Id)
)