CREATE FUNCTION udf_HoursToComplete(@startDate DATETIME, @endDate DATETIME)
RETURNS INT
AS
BEGIN
	IF (@startDate IS NULL)
	BEGIN
		RETURN 0
	END

	IF (@endDate IS NULL)
	BEGIN
		RETURN 0
	END

	RETURN DATEDIFF(HOUR, @startDate, @endDate)
END